### ISSUE TITLE
Repo name "mcwordle" pronunciation unclear

### ISSUE THREAD

**Issue by HarryXChen3** [WHEOfficial/mcwordle#1]
## Expected Behavior
It should be absolutely clear to the end user how to pronounce the name of this repository.

## Current Behavior
Although it is Minecraft related, the expected pronunciation remains vague and is not documented or specified.

## Possible Solution
Make the expected pronunciation of "mcwordle" absolutely clear in the repo because assumptions can be made about 2 (or more) possible pronunciations. Alternatively, the repo owner should provide an alternative pronunciation which is not part of the 2 expected pronunciations.

### There are 2 likely pronunciations
1. McDonalds -> McWordle so like read all together (MickWordle)
2. M.C. Wordle -> separated and distinct (EmmCee Wordle)

## Steps to Reproduce
1. Navigate to [mcwordle](https://github.com/WHEOfficial/mcwordle)
2. Read through [README.md](https://github.com/WHEOfficial/mcwordle/blob/main/README.md)
4. Realize that the pronunciation of "mcworld" is ambiguous and vague
5. Realize that there is no current documentation on the expected pronunciation

### Observed On
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
### Date
5/10/2023 @ 1004 EDT
1683727441
### Web Location
https://github.com/WHEOfficial/mcwordle

## Detailed Description

The repository name does not specify a pronunciation and remains vague as to what the expected pronunciation is. It is not immediately apparent what the socially accepted and repo owner designated pronunciation of "mcwordle" is, particularly of the "mc" part.

## Possible Implementation

Add a pronunciation guide with phonetics in the README.md file to document the expected pronunciation of "mcwordle"

**Comment by WHEOfficial** [comment]
Thank you for bringing this issue to my attention. I apologize to any individuals who struggled to pronounce the name of this repo. I have added an IPA pronunciation guide to the README to avoid any future confusion.
